---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-ws-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-ws-app
  policy:
    semver:
      range: v1.0.x

