apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: podinfo-service
spec:
  type: NodePort
  selector:
    app: podinfo
  ports:
    - port: 9898
      targetPort: 9898
      nodePort: 30007
